export const THINKING_VERBS = [
  'Accomplishing', 'Achieving', 'Acquiring', 'Actioning', 'Actualizing', 'Adjusting',
  'Advancing', 'Advocating', 'Alchemizing', 'Ambling', 'Analyzing', 'Approving',
  'Arranging', 'Arriving', 'Assessing', 'Attaining', 'Authenticating', 'Authorizing',
  'Backing', 'Baking', 'Balancing', 'Beaming', 'Beating', 'Boogieing', 'Booting',
  'Brainstorming', 'Brewing', 'Buffering', 'Buzzing', 'Calculating', 'Calibrating',
  'Captaining', 'Cerebrating', 'Certifying', 'Championing', 'Channeling', 'Charting',
  'Chasing', 'Choosing', 'Chugging', 'Chugging along', 'Churning', 'Clauding',
  'Coalescing', 'Coasting', 'Cogitating', 'Collaborating', 'Combing', 'Commanding',
  'Compiling', 'Computing', 'Concluding', 'Concocting', 'Conducting', 'Confirming',
  'Conjuring', 'Considering', 'Conspiring', 'Controlling', 'Cooking', 'Cooperating',
  'Coordinating', 'Crafting', 'Creating', 'Cruising', 'Crunching', 'Cultivating',
  'Daydreaming', 'Debugging', 'Deciding', 'Defragmenting', 'Deliberating', 'Deserving',
  'Determining', 'Developing', 'Dillydallying', 'Directing', 'Discovering', 'Distilling',
  'Divining', 'Doing', 'Doodling', 'Drafting', 'Drifting', 'Earning', 'Educating',
  'Effecting', 'Enchanting', 'Endorsing', 'Enlightening', 'Evaluating', 'Examining',
  'Executing', 'Expanding', 'Exploring', 'Exposing', 'Extending', 'Faffing', 'Fastening',
  'Fermenting', 'Fiddling', 'Finagling', 'Finessing', 'Finishing', 'Flexing', 'Floating',
  'Following', 'Forging', 'Forming', 'Fostering', 'Freestyling', 'Furthering', 'Futzing',
  'Gaining', 'Gallivanting', 'Generating', 'Getting', 'Gliding', 'Grabbing', 'Grasping',
  'Grinding', 'Grooving', 'Growing', 'Guiding', 'Handling', 'Hatching', 'Helming',
  'Hemming and hawing', 'Herding', 'Honking', 'Humming', 'Hunting', 'Hustling', 'Ideating',
  'Illuminating', 'Improvising', 'Incanting', 'Incubating', 'Inferring', 'Inspecting',
  'Instructing', 'Investigating', 'Invoking', 'Jamming', 'Jangling', 'Jingling', 'Juggling',
  'Justifying', 'Kneading', 'Laboring', 'Leading', 'Limbering', 'Loading', 'Locking',
  'Lollygagging', 'Managing', 'Manifesting', 'Mapping', 'Marinating', 'Massaging',
  'Materializing', 'Meandering', 'Meriting', 'Monitoring', 'Moseying', 'Motoring',
  'Mulling', 'Mustering', 'Musing', 'Navigating', 'Noodling', 'Nurturing', 'Obtaining',
  'Operating', 'Opting', 'Orchestrating', 'Ordering', 'Organizing', 'Outlining',
  'Overseeing', 'Percolating', 'Performing', 'Perusing', 'Picking', 'Piloting', 'Plotting',
  'Plucking', 'Pondering', 'Pottering', 'Prancing', 'Priming', 'Prioritizing', 'Probing',
  'Processing', 'Promoting', 'Pulsing', 'Pumping', 'Purring', 'Pursuing', 'Puttering',
  'Puzzling', 'Raking', 'Ranking', 'Rating', 'Reaching', 'Researching', 'Resolving',
  'Reticulating', 'Revealing', 'Revving', 'Riffing', 'Ruminating', 'Running', 'Sanctioning',
  'Sashaying', 'Sauntering', 'Sautéing', 'Scampering', 'Scheming', 'Schlepping', 'Scouring',
  'Scribbling', 'Scrutinizing', 'Sculpting', 'Searching', 'Seasoning', 'Securing', 'Seeking',
  'Seizing', 'Selecting', 'Sequencing', 'Settling', 'Shilly-shallying', 'Shimmying',
  'Shucking', 'Shuffling', 'Sifting', 'Simmering', 'Sketching', 'Slaving', 'Smooshing',
  'Snatching', 'Sorcering', 'Sorting', 'Spellcasting', 'Spinning', 'Steering', 'Stewing',
  'Stretching', 'Studying', 'Summoning', 'Supervising', 'Supporting', 'Swooshing', 'Syncing',
  'Synthesizing', 'Teaching', 'Teleporting', 'Thinking', 'Throbbing', 'Thrumming',
  'Tightening', 'Tinkering', 'Toiling', 'Tracking', 'Transmuting', 'Trotting', 'Trucking',
  'Tuning', 'Tweaking', 'Uncovering', 'Unraveling', 'Validating', 'Verifying', 'Vibing',
  'Waddling', 'Wafting', 'Wandering', 'Warming up', 'Warranting', 'Whipping', 'Whipping up',
  'Whirring', 'Whistling', 'Whittling', 'Whooshing', 'Winning', 'Wizarding', 'Woolgathering',
  'Working', 'Wrangling', 'Wrapping up', 'Yodeling', 'Zapping', 'Zipping', 'Zooming'
] as const;

export function getRandomThinkingVerb(): string {
  return THINKING_VERBS[Math.floor(Math.random() * THINKING_VERBS.length)];
}
