/**
 * E2E test: write_file tool can create files at ~/reports (outside cwd sandbox).
 *
 * Tests the full invocation path:
 *   input path → sandbox resolution → mkdir → writeFile → result
 *
 * Also covers: relative paths still sandboxed to cwd, escape attempts blocked.
 */
import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import { existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

// Import the tool func directly (bypasses LangChain wrapper overhead).
import { writeFileTool } from './write-file.js';

// Helpers
const HOME = homedir();
const REPORTS_DIR = join(HOME, 'reports');

function cleanupReport(filename: string) {
  const p = join(REPORTS_DIR, filename);
  try {
    rmSync(p);
  } catch {
    /* ok if already removed */
  }
}

// ---------------------------------------------------------------------------
// E2E: writing to ~/reports
// ---------------------------------------------------------------------------
describe('write_file E2E — ~/reports', () => {
  const TEST_FILE = 'dexter-e2e-test-report.md';
  const TEST_PATH = `~/reports/${TEST_FILE}`;
  const ABS_PATH = join(REPORTS_DIR, TEST_FILE);

  afterEach(() => {
    cleanupReport(TEST_FILE);
  });

  it('creates ~/reports/ directory automatically and writes the file', async () => {
    // ~/reports may or may not exist; the tool should create it.
    const content = `# Investment Thesis — AAPL\n\nGenerated by Dexter E2E test at ${new Date().toISOString()}\n`;

    const result = await writeFileTool.invoke({ path: TEST_PATH, content });
    const parsed = JSON.parse(result);

    expect(parsed.data.message).toContain('Successfully wrote');
    expect(existsSync(ABS_PATH)).toBe(true);
    expect(readFileSync(ABS_PATH, 'utf-8')).toBe(content);
  });

  it('reports correct bytesWritten', async () => {
    const content = 'Hello, ~/reports!\n';
    const result = await writeFileTool.invoke({ path: TEST_PATH, content });
    const parsed = JSON.parse(result);

    expect(parsed.data.bytesWritten).toBe(Buffer.byteLength(content, 'utf-8'));
  });

  it('overwrites an existing file', async () => {
    const first = '# First version\n';
    const second = '# Updated version\n';

    await writeFileTool.invoke({ path: TEST_PATH, content: first });
    await writeFileTool.invoke({ path: TEST_PATH, content: second });

    expect(readFileSync(ABS_PATH, 'utf-8')).toBe(second);
  });

  it('creates nested subdirectory under ~/reports', async () => {
    const nested = 'dexter-e2e-subdir/nested-report.md';
    const absNested = join(REPORTS_DIR, nested);
    const content = '# Nested report\n';

    try {
      const result = await writeFileTool.invoke({
        path: `~/reports/${nested}`,
        content,
      });
      const parsed = JSON.parse(result);
      expect(parsed.data.message).toContain('Successfully wrote');
      expect(existsSync(absNested)).toBe(true);
    } finally {
      rmSync(join(REPORTS_DIR, 'dexter-e2e-subdir'), { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// Sandbox: relative paths still work (relative to cwd)
// ---------------------------------------------------------------------------
describe('write_file sandbox — relative path (cwd)', () => {
  const CWD_TMP = join(process.cwd(), '.dexter-e2e-tmp');
  const TMP_FILE = join(CWD_TMP, 'test.md');

  afterEach(() => {
    rmSync(CWD_TMP, { recursive: true, force: true });
  });

  it('writes a relative path inside cwd', async () => {
    const content = '# relative test\n';
    const result = await writeFileTool.invoke({
      path: '.dexter-e2e-tmp/test.md',
      content,
    });
    const parsed = JSON.parse(result);
    expect(parsed.data.message).toContain('Successfully wrote');
    expect(existsSync(TMP_FILE)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Sandbox: escape attempts are blocked
// ---------------------------------------------------------------------------
describe('write_file sandbox — escape attempts blocked', () => {
  it('blocks ../.. relative traversal outside cwd', async () => {
    await expect(
      writeFileTool.invoke({ path: '../../etc/passwd', content: 'bad' }),
    ).rejects.toThrow(/sandbox/i);
  });

  it('blocks absolute path outside homedir', async () => {
    await expect(
      writeFileTool.invoke({ path: '/etc/dexter-test.txt', content: 'bad' }),
    ).rejects.toThrow(/sandbox/i);
  });
});
