/**
 * Dexter schedule command: headless job runner for scheduled research tasks.
 *
 * Config file: ~/.dexter/schedules.json
 * Usage:
 *   dexter-ts schedule list          — list configured jobs
 *   dexter-ts schedule run            — run all jobs
 *   dexter-ts schedule run <job-id>   — run a specific job
 */
import { readFile, writeFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import { Agent } from './agent/agent.js';

export interface ScheduleJob {
  /** Unique identifier used in `dexter-ts schedule run <id>` */
  id: string;
  /** Human-readable description shown in `schedule list` */
  description: string;
  /** Natural-language research query / skill invocation sent to the agent */
  query: string;
  /**
   * Output file path. Supports `{date}` which is replaced with today's ISO date
   * (YYYY-MM-DD). Paths starting with `~` are expanded to the home directory.
   */
  outputFile: string;
}

const SCHEDULES_PATH = join(homedir(), '.dexter', 'schedules.json');

const EXAMPLE_CONFIG: ScheduleJob[] = [
  {
    id: 'morning-briefing',
    description: 'Daily watchlist briefing',
    query: 'Run the watchlist-briefing skill for my portfolio',
    outputFile: '~/.dexter/reports/{date}-briefing.md',
  },
];

async function loadJobs(): Promise<ScheduleJob[]> {
  if (!existsSync(SCHEDULES_PATH)) {
    console.error(
      `No schedules config found at ${SCHEDULES_PATH}\n` +
        `Create it with:\n${JSON.stringify(EXAMPLE_CONFIG, null, 2)}`,
    );
    process.exit(1);
  }
  const raw = await readFile(SCHEDULES_PATH, 'utf-8');
  return JSON.parse(raw) as ScheduleJob[];
}

function resolveOutputPath(template: string): string {
  const date = new Date().toISOString().slice(0, 10);
  return template.replace('{date}', date).replace(/^~/, homedir());
}

async function runJob(job: ScheduleJob): Promise<void> {
  console.log(`\n▶ Running job "${job.id}": ${job.description}`);
  const outPath = resolveOutputPath(job.outputFile);
  const outDir = outPath.slice(0, outPath.lastIndexOf('/'));
  if (outDir) await mkdir(outDir, { recursive: true });

  const agent = await Agent.create();
  let answer = '';

  for await (const event of agent.run(job.query)) {
    if (event.type === 'tool_start') {
      console.log(`  ⚙ ${event.tool}(${JSON.stringify(event.args ?? {}).slice(0, 80)})`);
    } else if (event.type === 'answer_chunk') {
      process.stdout.write(event.chunk);
      answer += event.chunk;
    } else if (event.type === 'done') {
      if (!answer) answer = event.answer ?? '';
      console.log(`\n✓ Job complete (${event.iterations} iterations, ${event.totalTime}ms)`);
    }
  }

  if (!answer) {
    console.error(`✗ Job "${job.id}" produced no answer.`);
    return;
  }

  const header = `# ${job.description}\n_Generated by Dexter — ${new Date().toISOString()}_\n\n`;
  await writeFile(outPath, header + answer, 'utf-8');
  console.log(`\n💾 Output saved to ${outPath}`);
}

function printUsage(): void {
  console.log(
    [
      'Usage:',
      '  dexter-ts schedule list          — list configured jobs',
      '  dexter-ts schedule run            — run all jobs',
      '  dexter-ts schedule run <job-id>  — run a specific job',
      '',
      `Config: ${SCHEDULES_PATH}`,
    ].join('\n'),
  );
}

export async function runScheduleCommand(argv: string[]): Promise<void> {
  const [subCmd, jobId] = argv; // e.g. ['run', 'morning-briefing'] or ['list']

  if (!subCmd || subCmd === 'help' || subCmd === '--help') {
    printUsage();
    return;
  }

  if (subCmd === 'list') {
    const jobs = await loadJobs();
    console.log(`\nConfigured jobs (${SCHEDULES_PATH}):\n`);
    for (const job of jobs) {
      console.log(`  ${job.id.padEnd(24)} ${job.description}`);
      console.log(`  ${''.padEnd(24)} output: ${job.outputFile}\n`);
    }
    return;
  }

  if (subCmd === 'run') {
    const jobs = await loadJobs();
    const targets = jobId ? jobs.filter((j) => j.id === jobId) : jobs;

    if (jobId && targets.length === 0) {
      console.error(`No job found with id "${jobId}". Run \`dexter-ts schedule list\` to see available jobs.`);
      process.exit(1);
    }

    for (const job of targets) {
      await runJob(job);
    }
    return;
  }

  console.error(`Unknown subcommand: "${subCmd}"`);
  printUsage();
  process.exit(1);
}
